FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY api/ api/
COPY pkg/ pkg/
COPY cmd/api/ cmd/api/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o api cmd/api/main.go

FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY --from=builder /app/api .

EXPOSE 8080

USER 65532:65532

ENTRYPOINT ["/api"]
