FROM golang:1.23 AS builder
WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY api/ api/
COPY internal/ internal/
COPY cmd/operator/ cmd/operator/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o operator cmd/operator/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/operator .
USER 65532:65532
ENTRYPOINT ["/operator"]
