apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator
rules:
- apiGroups: ["email.example.com"]
  resources: ["emails", "emailsenderconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["email.example.com"]
  resources: ["emails/status", "emailsenderconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
